version: '3.9'

volumes: 
  aris_home: {}
  var-logs: {}

services:
  aris-box:
    image: my-aris-playground
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        - __install_dir=${ARIS_INSTALL_DIR}
    ulimits:
      nproc: 12204
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - ./scripts/:/mnt/scripts/
      - aris_home:${ARIS_INSTALL_DIR}
      - var-logs:/var/logs/
      - ${H_ARIS_INSTALLATION_BIN_CLOUD_AGENT}:/tmp/cloud-agent.rpm
      - ${H_ARIS_INSTALLATION_BIN_ACC}:/tmp/acc.rpm
      - ${H_ARIS_INSTALLATION_BIN_ADMIN}:/tmp/admin.rpm
      - ${H_ARIS_INSTALLATION_BIN_SCRIPT_RUNNER}:/tmp/script-runner.rpm
    environment:
      - name=value
    ports:
      - 14000:14000
    entrypoint: /mnt/scripts/entrypoint.sh
