version: '3.9'

volumes:
  # home and logs folder for aris design server installation via cloud agent in the aris box
  aris_server_home: {}
  var-logs: {}
  # common share for collaboration of scripts (wip)
  common: {}

# TODO: host kernel must be set for Elasticsearch, e.g. with the vm.max_map_count properly set to at least 262144

services:
  aris:
    image: my-aris-playground
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        - __install_dir=${ARIS_INSTALL_DIR}
    ulimits:
      nproc: 12204
      nofile:
        soft: 1048576
        hard: 1048576
    hostname: aris
    volumes:
      - ./scripts/aris-server/:/mnt/scripts/
      - aris_server_home:${ARIS_INSTALL_DIR}
      - var-logs:/var/logs/
      - common:/mnt/common/
      - ${H_ARIS_INSTALLATION_BIN_CLOUD_AGENT}:/tmp/cloud-agent.rpm
      - ${H_ARIS_INSTALLATION_BIN_ACC}:/tmp/acc.rpm
    ports:
      - 14000:14000
    entrypoint: /mnt/scripts/entrypoint.sh


  ## This is only needed during setup
  # See chapter 3.10 in the Distributed Installation Cookbook
  setup-repo:
    image: nginx
    ports:
      - 18000:80
    volumes:
      - ${H_ARIS_COM_INSTALL_FOLDER}:/www/data/
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
